### ISSUE TITLE
Can you update it, please?

### ISSUE THREAD

**Issue by dxps** [creativetimofficial/ct-muse-vue-ant-design-dashboard-pro#2]
Hi Creative Tim team!

I used to buy some of your themes in the past and I am seriously consider buying this one as well.

Before that though, could you please update it to the current versions of Vue and Ant Design Vue?
I see that currently it uses:
- Vue 2 (v2.6.14) instead of 3
- Vue Router 3 instead of 4
- most probably And Design Vue ver. 2.x

Thanks!

**Comment by dxps** [comment]
Yeah, alright, I'll use that path.

**Comment by dxps** [comment]
But since I haven't bought it, i don't have a proper Order ID, so I can't even submit this as a _Feature Request_. :disappointed:

**Comment by dragosct** [comment]
Hi, @dxps! Thanks for using our products. It's a complex update here and it will be made but for the moment we don't have an ETA for it, unfortunately.

**Comment by dxps** [comment]
Thanks Dragoș! :pray: 

I was expecting this. But since I used to use (and love) And Design, I shall start playing and trying such upgrade with [the non Pro version](https://www.creative-tim.com/product/muse-vue-ant-design-dashboard) and see how it goes.

Appreciate the feedback! :blush:

**Comment by tanhh326** [comment]
When will the vue3 version be released? This is very nice and I want to use it to build a personal site.
